name: production-deployment
# Trigger condition can be update per your preference

on:
  workflow_dispatch:
    branches:
      - develop
    inputs:
      confirm_message:
        description: "***WARNING: This workflow executes a deployment to a production environment. Please type 'production' to confirm.***"
        required: true

jobs:
  deployment:
    name: Build and upload files to the s3 buckets
    runs-on: ubuntu-latest
    steps:

      - name: Check confirm_message
        run: |
          if [ "${{ github.event.inputs.confirm_message }}" != 'production' ]; then
            echo "You must check WARNING message!"
            exit 1
          fi
