name: production-deployment
# Trigger condition can be update per your preference

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: Your message
        required: true
    branches:
      - master

jobs:
  deployment:
    name: Build and upload files to the s3 buckets
    runs-on: ubuntu-latest
    steps:

      - name: echo
        run: |
          echo "hello gh actions for PROD"
