name: staging-deployment
# Trigger condition can be update per your preference

on:
  workflow_dispatch:

jobs:
  deployment:
    name: Build and upload files to the s3 buckets
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "hello gh actions for STG"
